---
- hosts: centosnode
  tasks:
  - name: Add Elasticsearch key
    rpm_key:
     key: "https://packages.elastic.co/GPG-KEY-elasticsearch"
     state: present

# Add the Elasticsearch apt repo. For versions 6 of the stack - use '6.x-prerelease':

  - name: copy files
    copy: src=/root/sunita/elk.repo dest=/etc/yum.repos.d

  - name: install elasticsearch
    yum:
      name: elasticsearch
      state: latest
      update_cache: yes

# Update Elasticsearch config file to allow access (to secure Elasticsearch, bind to 'localhost').

  - name: Updating the config file to allow outside access
    lineinfile:
     destfile: /etc/elasticsearch/elasticsearch.yml
     regexp: 'network.host:'
     line: 'network.host: 0.0.0.0'

# Update Elasticsearch port in config file

  - name: Updating the port in config file
    lineinfile:
     destfile: /etc/elasticsearch/elasticsearch.yml
     regexp: 'http.port:'
     line: 'http.port: 9200'

# Start Elasticsearch
  - name: Starting Elasticsearch
    service:
     name: elasticsearch
     state: started
  - name: Install Kibana with yum
    yum:
     name: kibana
     state: latest
     update_cache: yes

# Configurations

  - name: Updating the config file to allow outside access
    lineinfile:
     destfile: /etc/kibana/kibana.yml
     regexp: 'server.host:'
     line: 'server.host: 0.0.0.0'

  - name: Defining server port
    lineinfile:
     destfile: /etc/kibana/kibana.yml
     regexp: 'server.port:'
     line: 'server.port: 5601'

  - name: Defining Elasticsearch URL
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'elasticsearch.url:'
      line: 'elasticsearch.url: "http://localhost:9200"'

# Starting Kibana

  - name: Starting Kibana
    service:
     name: kibana
     state: started

